# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
permissions: write-all
on:
  schedule: 
    - cron: "*/17 * * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.18"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: bot
      run: |
        cd src/
        python test.py
        python bey-vinted-bot.py

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        # Stage the file, commit and push
        git add *
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
            # Commit changes with a message
            git commit -m "new data added by bot in history"
            # Push changes to the remote repository
            git push origin main
        else
            echo "Nothing to commit."
        fi
        
